name: "PR validation"
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches-ignore:
      - staging
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Pipenv
        run: pip install --user pipenv
      - name: Install Dependencies
        run: pipenv install
      - name: Run Tests
        run: pipenv run python manage.py test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: open5e-api:${{ github.ref_name }}
