name: "PR validation"
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches-ignore:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: open5e-api:${{ env.GITHUB_REF_NAME }}
